apiVersion: v1
kind: Service
metadata:
  name: space-gateway-backend
  labels:
    app: space-gateway-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: space-gateway-backend 